# The sequence of triangle numbers is generated by adding the natural
# numbers. So the 7th triangle number would be:
#   1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#   1: 1
#   3: 1,3
#   6: 1,2,3,6
#   10: 1,2,5,10
#   15: 1,3,5,15
#   21: 1,3,7,21
#   28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?
#
# @see https://projecteuler.net/problem=12

def factors_for(value)
  factors = [1, value]
  Math.sqrt(value).to_i.downto(2).each do |i|
    if value % i == 0
      factors << i
      factors << value / i
    end
  end
  factors.sort
end

STOP_AT = 500
i = 0
triangle_number = 0
factors = []

while true
  i += 1
  triangle_number += i
  factors = factors_for(triangle_number)
  break if factors.size >= STOP_AT
end
puts triangle_number
